name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh-action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/Warship-studio-front-end/warship-studio-website
            git stash push -m "discard local changes"
            git pull
            export NVM_DIR="$HOME/.nvm"
            . "$NVM_DIR/nvm.sh"
            echo "==================== Showing PATH after git pull ===================="
            echo $PATH
            source ~/.bashrc
            echo "==================== Showing PATH after sourcing ===================="
            echo $PATH
            npm install
            npm run build
            pm2 restart next-js
